### ISSUE TITLE
docker-compose up -d starts the weaviate container, but fails to start the Verba container

### ISSUE THREAD

**Issue by twilwa** [weaviate/Verba#104]
![image](https://github.com/weaviate/Verba/assets/111034762/2f379742-83fc-43d1-bbc5-39a29416f87e)
Here's the error logs the container's spitting out -- my other containers work fine. I'm poking through the codebase and made sure my .env.example was set and renamed. I'm starting Verba in a WSL2 environment -- but as far as I know, that shouldn't matter for Docker.

Looking into it a bit, I had Codium analyse for issues -- not sure if it's helpful as I'm not super familiar with the codebase yet.
![image](https://github.com/weaviate/Verba/assets/111034762/a5ea37b8-f5f6-4daa-9d29-4b1860d5a1d6)

**Comment by jcranney** [comment]
It could be unrelated, but the Docker Compose V2 syntax is without the hyphen, e.g.,:
```bash
docker compose up -d 
```
instead of the old `docker-compose up -d` syntax. More info about the difference can be found in the [Docker docs](https://docs.docker.com/compose/migrate/).  If you are running an old version of Docker this syntax might not work at first, see [docs on installing new Compose](https://docs.docker.com/compose/install/).

Additionally, if you are changing the `.env` file you will need to rebuild your images each time:
```bash
docker compose up -d --build
```

I hope this helps!

**Comment by twilwa** [comment]
Looks like this seems to have resolved itself at some point -- however, i'm now experiencing #108 when trying to run locally and 
![image](https://github.com/weaviate/Verba/assets/111034762/2726dae3-301f-40b4-9f96-86fd6500d42e)
the attached image when attempting to run via docker.

**Comment by thomashacker** [comment]
We're aware of this issue and will fix it soon! thanks for the issue 🚀

**Comment by thomashacker** [comment]
Should be fixed with the latest release! 🚀
