### ISSUE TITLE
Running into import errors

### ISSUE THREAD

**Issue by moefarag1** [weaviate/Verba#117]
Hi Guys,

I am trying to import a .pdf which has the size of 7.7MB.

I've tried using the different settings but have been unable to import. I'm currently using the Token Chunker with 250 units and an overlap of 50.

Chunk mismatch for 3c161a37-d99a-4f2c-9c54-a7db5275e217 0 != 4527

[Site Reliability Engineering.pdf](https://github.com/weaviate/Verba/files/14364353/Site.Reliability.Engineering.pdf)

**Comment by Shmoji** [comment]
running into same thing. Not just with PDF, but anything i try with any mix of settings

**Comment by thomashacker** [comment]
Thanks for the issue! We'll look into that

**Comment by sitaram70** [comment]
my 2 cents!
Did you use docker compose?
I am able to upload files using docker compose.

This is what I did:
1. Stop and Delete docker containers for Verba and Weaviate
2. Delete the Docker images for Verba and Weaviate
3. I deletes volumes also
4. Then using git, cloned the latest version and made the required changes
5. ran the docker compose

It worked fine,

**Comment by thomashacker** [comment]
The newest update v1.0.0 has better ingestion support and capabilities. I was able to ingest your .pdf, let me know if this error still persists for you

**Comment by sumant-28** [comment]
I can't import the original txt document I wanted nor the PDF referenced above for what it's worth

**Comment by thomashacker** [comment]
Did you update to the latest release? What error messages are you receiving?

**Comment by xdba-jimeta** [comment]
I am using 1.25.0 and I am unbale to import a 5mb pdf file with various chunking settings.  Using embedded Weaviate, tried both docker and pip based install but gettign the same results. I am using the default ADAEmbedder in verba.

**Comment by thomashacker** [comment]
Are you receiving any errors?

**Comment by xdba-jimeta** [comment]
Yes, I get the chunk mismatch error, regardless of setting used with pdf larger than about ~5Mb

**Comment by sumant-28** [comment]
I tried again recently with the same error

**Comment by sumant-28** [comment]
I was able to do an import using the Ollama rather openai engine. It seems that could be an issue or possibly with my .env file. Either way this is not what I would call user friendly for someone who is only a novice when it comes to things like local servers

**Comment by xdba-jimeta** [comment]
What size file were you able to import with ollama?
 

 
  
 
   On Thu, Jun 20, 2024, 06:51 AM Sumanth Athreya Seshasayee ***@***.***> wrote: 
   
  
  
   
  I was able to do an import using the Ollama rather openai engine. It seems that could be an issue or possibly with my .env file. Either way this is not what I would call user friendly for someone who is only a novice when it comes to things like local servers 
  —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***> 
  [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/weaviate/Verba/issues/117#issuecomment-2180381364",
"url": "https://github.com/weaviate/Verba/issues/117#issuecomment-2180381364",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
