### ISSUE TITLE
silly question, but how to delete cached environment variables that verba's using?

### ISSUE THREAD

**Issue by twilwa** [weaviate/Verba#141]
hey, openai reset everyone's api keys and moved them to project-based keys, and i can't for the life of me figure out how to get verba to update to the new env var. I've tried the following:

update .env
export OPENAI_API_KEY=newkey
delete browser cookies and cache
change to a different browser (chrome to edge)
create a new virtualenv
uninstall goldenverba, reinstall with --no-cache flag

seems like no matter what I do i'm getting the unserializable object error (which iirc means my api key is incorrect, but it's difficult to tell for certain as i'm not displayed the error code.

**Comment by thomashacker** [comment]
Hey! I also struggled with this 🥲 Here are some tips I used to get it working, I hope they can help:

1. Make sure that the `OPEN_API_KEY` is not stored in `~/.zshrc`, `~/.bash_profile`, etc. `python_dotenv` will always prioritize global set variables to local `.env` files
2.  You can use `printenv` outside your working dir to print all environment variables
3. If `OPEN_API_KEY` is only stored  in your `.env`, try to use `source .env` before starting verba, it will make sure that it uses the updated keys instead of any cached one.

Let me know if this helped fix things 🚀
