### ISSUE TITLE
Azure Open AI - Resource Not Found and Chunk Mismatch

### ISSUE THREAD

**Issue by Tansif** [weaviate/Verba#186]
I am trying to integrate Azure Open AI and using these below environment variables for the verba and weaviate but getting 404 error: Resource not found. Also in UI: Embedding not successful: Chunk mismatch for 51** 0 != 14 , 

verba:
   environment:
      - WEAVIATE_URL_VERBA=http://weaviate:8080
      - OPENAI_API_TYPE="azure"
      - OPENAI_API_KEY=c*
      - OPENAI_BASE_URL=https://rr.openai.azure.com/
      - AZURE_OPENAI_RESOURCE_NAME=rr
      - AZURE_OPENAI_EMBEDDING_MODEL="text-embedding-ada-002"
      - OPENAI_MODEL="gpt-35-turbo"
      - OPENAI_API_VERSION="2023-03-15-preview"
      - WAIT_TIME_BETWEEN_INGESTION_QUERIES_MS=100
      
  weaviate:
    environment:
          QUERY_DEFAULTS_LIMIT: 25
          AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
          PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
          ENABLE_MODULES: 'text2vec-openai, generative-openai, qna-openai, text2vec-cohere'
          CLUSTER_HOSTNAME: 'node1'
          
  Did anyone face the same issue?

**Comment by thomashacker** [comment]
Thanks for the issue! Did you install Verba from source?

**Comment by schoi80** [comment]
I can confirm the same issue on my end.  This what I see in the log
![image](https://github.com/weaviate/Verba/assets/1744194/75be2361-9e6c-42be-84db-6dcb4d70d5d9)

**Comment by Tansif** [comment]
> Thanks for the issue! Did you install Verba from source?

I am using Docker for the deployment.

**Comment by Tansif** [comment]
> Thanks for the issue! Did you install Verba from source?

I am using Docker for the deployment.

**Comment by thomashacker** [comment]
Thanks for the issue! there seems to be an issue with the azure implementation, we're looking into it

**Comment by onlineorchid** [comment]
Running into the same error, using Docker, Weaviate Embedded and OPENAI API KEY (Not Azure):

_(INFO) Importing...
(INFO) Importing 1 files with BasicReader
(INFO) Importing Test .pdf
(SUCCESS) Loaded 1 documents in 0.87s
(INFO) Starting Chunking with TokenChunker
(SUCCESS) Chunking completed with 104 chunks in 0.05s
(INFO) Starting Embedding with ADAEmbedder
(ERROR) Embedding not successful: Chunk mismatch for ec0d2ac5-c733-4f1d-ae2f-f1b227a9ffac 0 != 104
(ERROR) Chunk mismatch for ec0d2ac5-c733-4f1d-ae2f-f1b227a9ffac 0 != 104_

**Comment by liqingqing562** [comment]
Has the problem been solved? @Tansif 
I had the same problem，Below is a screenshot of my journal
--
dial tcp: lookup https on xx.xx.xx.xx:53: no such host'}]}, 'status':
'FAILED'}

**Comment by Tansif** [comment]
> ## Has the problem been solved? @Tansif
> I had the same problem，Below is a screenshot of my journal
> dial tcp: lookup https on xx.xx.xx.xx:53: no such host'}]}, 'status': 'FAILED'}

not yet @liqingqing562

**Comment by DWDNZ001** [comment]
Hi, looks like its calling the old API's, could be due to using the retired version of of the OpenAI Python package
Current == openai 1.34.0
Verba == openai-0.27.9 

"https://XXXXXXXXXXXXXX-XXXXXX-XXX/openai/deployments/text-embedding-ada-002/embeddings?_**api-version=2022-12-01":**_
dial tcp: lookup XXXXXXXXXXXXXX-XXXXXX-XXX.openai.azure.com on 127.0.0.53:53: no such
host'}]}, 'status': 'FAILED'}

[https://learn.microsoft.com/en-us/azure/ai-services/openai/reference]

2023-03-15-preview (retiring July 1, 2024) Swagger spec
**2023-05-15** Swagger spec
2023-06-01-preview Swagger spec
2023-07-01-preview (retiring July 1, 2024) Swagger spec
2023-08-01-preview (retiring July 1, 2024) Swagger spec
2023-09-01-preview (retiring July 1, 2024) Swagger spec
2023-10-01-preview Swagger spec
2023-12-01-preview (retiring July 1, 2024) Swagger spec
2024-02-15-previewSwagger spec
2024-03-01-preview Swagger spec
2024-04-01-preview Swagger spec
2024-05-01-preview Swagger spec
2024-02-01 Swagger spec
