### ISSUE TITLE
Documents with same filename get mixed up by window retriever

### ISSUE THREAD

**Issue by jamesoflol** [weaviate/Verba#214]
## Description
I've imported multiple documents with the same filename - README.md. The window retriever seems to be randomly mixing up chunks from each of them into one document retrieval result.

## Is this a bug or a feature?
- [x] Bug
- [ ] Feature

It appears the window retriever looks up neighbouring chunks by doc_name, rather than by the document's unique ID. This happens when building context for a single document, but it seems that the context generator also doesn't even try to include additional documents even though multiple were found in the db similarity lookup. I.e., if there's 3 README.md files returned in the lookup, clicking the "See Context" button still only shows a single line that reads "--- Document README.md ---", rather than 3.

**Comment by 13777469818** [comment]
unsubscribe
 
From: James Hale
Date: 2024-06-03 13:51
To: weaviate/Verba
CC: Subscribed
Subject: [weaviate/Verba] Documents with same filename get mixed up by window retriever (Issue #214)
Description
I've imported multiple documents with the same filename - README.md. The window retriever seems to be randomly mixing up chunks from each of them into one document retrieval result.
Is this a bug or a feature?
Bug
Feature
It appears the window retriever looks up neighbouring chunks by doc_name, rather than by the document's unique ID. This happens when building context for a single document, but it seems that the context generator also doesn't even try to include additional documents even though multiple were found in the db similarity lookup. I.e., if there's 3 README.md files returned in the lookup, clicking the "See Context" button still only shows a single line that reads "--- Document README.md ---", rather than 3.

**Comment by thomashacker** [comment]
Hmm, you shouldn't be able to import documents with the same name in the first place; that's interesting! But I agree, the WindowRetriever should rather look at the uuid instead of the doc name

**Comment by thomashacker** [comment]
This should be fixed in the newest release!
