### ISSUE TITLE
How to install HuggingFace dependencies in Docker

### ISSUE THREAD

**Issue by LuciAkirami** [weaviate/Verba#84]
I want to use the huggingface llama2 model through the HuggingFace API in Verba. I have the Verba docker container up and running. But in the status bar I see that the huggingface libraries like the `huggingface_hub`, `transformers` are not installed.

By the way the `sentence-transformers` is missing an `s` in the requirements.txt

One way I tried was to go inside the docker container container and run the `pip install -r requirements.txt` to install the libraries. By the way does using the HuggingFace downloads the entire Llama2 model? or is there an option to use the HuggingFace Inference API?

**Comment by thomashacker** [comment]
Nice catch, thanks! I changed the Dockerfile configuration so that it also downloads the HuggingFace stack. Right now, Verba does not support the HuggingFace Inference API but we're working on it! 

To use the Llama model you need to configure the `LLAMA2-7B-CHAT-HF` to `true`, this will download the 7B model from Huggingface. We're also working on optimizing the code, and also include libraries like Ollama and Llama.cpp

**Comment by LuciAkirami** [comment]
Cool, that's great to hear. Would be great if added support to the quantized models as well
