### ISSUE TITLE
Delete a previously uploaded document

### ISSUE THREAD

**Issue by trungtly** [weaviate/Verba#87]
Hi Team,

Thanks for the great product. I need to delete a previously uploaded document from the verba document collection, not sure how this can be done?

**Comment by cam-barts** [comment]
Hi there @trungtly. In order to delete a document, you can first click the "Documents" tab here:
![image](https://github.com/weaviate/Verba/assets/13058567/8d85d5c9-c13f-4b1b-9c33-653d9397e893)

Then you should find the document you wish to delete and select it from the left panel. You should see a preview in the right panel when you select your document. Once the document is selected, there is an option in the top of the left panel to delete the document: 
![image](https://github.com/weaviate/Verba/assets/13058567/36bc5703-6ad2-4dba-a16f-77cf6219c39b)

Does this help?
